const AdminResponseConst = {
  AdminSignupSuccessfully: "Admin signed up successfully.",
  AdminNotFound: "Admin not found with the provided email.",
  InvalidCredentials: "Invalid email or password.",
  AdminSignInSuccessfully: "Admin signed in successfully.",
  AccessDenied: "Access denied. Admin authentication required.",
  UsersFetchedSuccessfully: "Users fetched successfully.",
  PoojaCreatedSuccessfully: "Pooja created successfully",
  PoojasRetrievedSuccessfully: "Poojas retrieved successfully",
  PoojaDeletedSuccessfully: "Pooja deleted successfully",
  PoojaUpdatedSuccessfully: "Pooja updated successfully",
  TempleCreated: "Temple created successfully",
  TemplesDetailsFetched: "Temples details fetched successfully",
  TempleDeleted: "Temple deleted successfully",
  SouvernirCreated: "Souvernir created successfully",
  SouvernirsFetched: "Souvernirs fetched successfully",
  SouvernirDeletedSuccessfully: "Souvernir deleted successfully",
  SouvernirUpdatedSuccessfully: "Souvernir updated successfully",
  UserSuspendedStatusUpdated: "User suspended status updated successfully",
  ReligionCreatedSuccessfully: "Religion created successfully",
  ReligionsFetchedSuccessfully: "Religions fetched successfully",
  ReligionDeletedSuccessfully: "Religion deleted successfully",
  ReligionUpdatedSuccessfully: "Religion updated successfully",
  ReligionNotFound: "Religion not found",
  ReligionFetchedSuccessfully: "Religion fetched successfully",
  HowWePrayCreatedSuccessfully: "How we pray item created successfully",
  PrayImageIsRequired: "prayImage is required",
  HowWePrayFetchedSuccessfully: "How we pray items fetched successfully",
  HowWePrayDeletedSuccessfully: "How we pray item deleted successfully",
  ItemNotFound: "Item not found",
  HowWePrayUpdatedSuccessfully: "How we pray item updated successfully",
  SouvernirImageIsRequired: "Souvernir image is required",
  TempleImageIsRequired: "Temple image is required",
  TempleUpdatedSuccessfully: "Temple updated successfully",
  TempleNotFound: "Temple not found",
  PriestsRetrievedSuccessfully: "Priests retrieved successfully",
  BookingsDetailsFetchedSuccessfully: "Bookings details fetched successfully",
  ImageNotFound: "Image not found",
  ImageDeletedSuccessfully: "Image deleted successfully",
  ImageUploadedSuccessfully: "Image uploaded successfully",
  OfferingCreatedSuccessfully: "Offering created successfully",
  DonationsFetchedSuccessfully: "Donations fetched successfully",
  DonationCreatedSuccessfully: "Donation created successfully",
  DonationDeletedSuccessfully: "Donation content deleted successfully",
  DonationUpdatedSuccessfully: "Donation content updated successfully",
  OfferingsFetchedSuccessfully: "Offerings fetched successfully",
  OfferingDeletedSuccessfully: "Offering deleted successfully",
  OfferingUpdatedSuccessfully: "Offering updated successfully",
  OfferingImageDeletedSuccessfully: "Offering image deleted successfully",
  OfferingImageUploadedSuccessfully: "Offering image/s uploaded successfully",
  BankCreatedSuccessfully: "Bank created successfully",
  FinanceDashboardDataFetchedSuccessfully:
    "Finance dashboard data fetched successfully",
  AdminNotApproved: "Admin account is not approved yet.",
  PriestPaymentSummeryDetailsFetchedSuccessfully:
    "Priest payment summery details fetched successfully",
  PriestPaymentStatusDetailsFetchedSuccessfully:
    "Priest payment status details fetched successfully",
  PriestEarningPaymentStatusUpdatedSuccessfully:
    "Priest earning payment status updated successfully",
  PasswordChangedSuccessfully: "Password changed successfully",
  CurrentPasswordIncorrect: "Current password is incorrect",
  AccessTokenRefreshedSuccessfully: "Access token refreshed successfully",
  AdminSignOutSuccessfully: "Admin signed out successfully",
  FailedToSignOut: "Failed to sign out",
  BanksRetrievedSuccessfully: "Banks retrieved successfully",
  BankDeletedSuccessfully: "Bank deleted successfully",
};

export default AdminResponseConst;
