const responseConstants = {
  UserSignUpSuccess: "User signed up successfully",
  UserSignUpError: "An error occurred during signup",
  UserSignInSuccess: "User signed in successfully",
  UserSignInError: "An error occurred during signin",
  InvalidUsernameOrPassword: "Invalid username or password",
  UserNotFound: "User not found",
  UserProfileDetailsUpdated: "User profile details updated successfully",
  DevoteeRetrievedSuccessfully: "Devotees retrieved successfully",
  DevoteeCreatedSuccessfully: "Devotee created successfully",
  DevoteeDeletedSuccessfully: "Devotee deleted successfully",
  DevoteeUpdatedSuccessfully: "Devotee updated successfully",
  PoojaBookingCreatedSuccessfully: "Pooja booking created successfully",
  UserDetailsFetched: "User details fetched successfully",
  UserBillingAddressAdded: "User billing address added successfully",
  UserBillingAddressRetrieved: "User billing address retrieved successfully",
  BookingCalculationDetailsFetched:
    "Booking calculation details fetched successfully",
  PoojaNotFound: "Pooja not found",
  CancelledPoojaBookingsFetched:
    "Cancelled pooja bookings fetched successfully",
  BookingIdRequired: "Booking ID is required",
  BookingNotFound: "Booking not found",
  PoojaBookingCancelledSuccessfully: "Pooja booking cancelled successfully",
  UpcomingPoojaBookingsFetched: "Upcoming pooja bookings fetched successfully",
  PreviousPoojaBookingsFetched: "Previous pooja bookings fetched successfully",
  PaymentVerifiedSuccessfully: "Payment verified successfully",
  PaymentVerificationFailed: "Payment verification failed",
  poojaBookingDetailsCreated: "Pooja booking details created successfully",
  PoojaAddedToFavorites: "Pooja added to favorites successfully",
  UserFavouritePoojaAndTemplesRetrieved:
    "User's favourite pooja and temples retrieved successfully",
  PoojaAlreadyInFavorites: "Pooja is already in favorites",
  TempleAddedToFavorites: "Temple added to favorites successfully",
  TempleAlreadyInFavorites: "Temple is already in favorites",
  TempleNotFound: "Temple not found",
  PoojaNotFound: "Pooja not found",
  PoojaRemovedFromFavorites: "Pooja removed from favorites successfully",
  TempleRemovedFromFavorites: "Temple removed from favorites successfully",
  SouvernirDetailsRequired: "Souvernir details are required",
  SouvernirNotFound: "Souvernir not found",
  PoojaRetrievedSuccessfully: "Pooja retrieved successfully",
  TempleDetailsFetched: "Temple details fetched successfully",
  OfferingsFetched: "Offerings fetched successfully",
  OfferingsIDNotFound: "Offering ID is required",
  OfferingsNotFound: "Offerings not found",
  OfferingsCreated: "Offering created successfully",
  OfferingsFetched: "Offerings fetched successfully",
  OfferingsDeletedSuccessfully: "Offering deleted successfully",
  OfferingsUpdatedSuccessfully: "Offering updated successfully",
  OfferingsDetailsRequired: "Offerings details are required",
  OfferingsNotFound: "Offerings not found",
  SouvernirDetailsFetched: "Souvernir details fetched successfully",
  RatingsRetrievedSuccessfully: "Ratings retrieved successfully",
  RatingCreatedSuccessfully: "Rating created successfully",
  BookingsFetched: "Pooja bookings fetched successfully",
  ForgotPasswordLinkSent: "Forgot password link sent successfully",
  PasswordReset: "Password Successfully Reset",
  PriestIntroductionAddedSuccessfully: "user introduction added successfully",
  UserIsAPriest: "User priest status fetched successfully",
  UserPaymentDetailsAddedSuccessfully:
    "User payment details added successfully",
  UserPaymentDetailsUpdatedSuccessfully:
    "User payment details updated successfully",
  AccountDetailsFetched: "User Account details fetched successfully",
  UserSuspended: "Your account is suspended. Please contact support center.",
  UserDeactivated:
    "Your account is deactivated. Please contact support center.",
  ReligionsFetchSuccess: "Religions fetched successfully",
  DataFetchSuccess: "Data fetched successfully",
  DonationCreatedSuccessfully: "User donation created successfully",
  PaymentPending: "Payment is pending",
  PaymentAuthorized: "Payment is authorized",
  PaymentRefunded: "Payment is refunded",
  PaymentUnknown: "Payment status is unknown",
  PasswordChangedSuccessfully: "Password changed successfully",
  OfferCreatedSuccessfully: "Offering created successfully",
};

export default responseConstants;
